-- ====================================================================
-- Flyway / PostgreSQL Migration: V1.0.2__seed_movies.sql
-- Description: Batch seed 12 realistic curated blockbusters (6 NOW_SHOWING, 6 COMING_SOON)
-- Compatible with PostgreSQL 16
-- ====================================================================

INSERT INTO movies (title, synopsis, genre, duration_minutes, age_rating, language, poster_url, trailer_url, release_date, status)
VALUES
-- 6 FILM YANG SEDANG TAYANG HARI INI (status = NOW_SHOWING)
('Dune: Part Two', 'Paul Atreides bersatu dengan Chani dan Fremen selagi mencari cara untuk membalas dendam terhadap para konspirator yang menghancurkan keluarganya. Menghadapi pilihan antara cinta dan takdir alam semesta, ia berjuang mencegah masa depan mengerikan.', 'Sci-Fi, Adventure, Action', 166, '13+', 'English / Sub ID', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/Way9Dexny3w', '2024-02-28', 'NOW_SHOWING'),
('Exhuma', 'Seorang dukun terkenal dan pengusir setan disewa oleh keluarga kaya untuk menyelidiki kuburan leluhur yang misterius. Namun saat ritual pembongkaran makam dilakukan, mereka justru membangkitkan kekuatan gelap yang mematikan.', 'Horror, Mystery, Thriller', 134, '17+', 'Korean / Sub ID', 'https://images.unsplash.com/photo-1509248961158-e66394016766?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/3H4VbHhY8R0', '2024-02-28', 'NOW_SHOWING'),
('Godzilla x Kong: The New Empire', 'Dua titan raksasa, Godzilla dan Kong, harus bersatu untuk menghadapi ancaman kolosal yang tersembunyi di dalam perut Bumi. Ancaman purba ini tidak hanya menantang eksistensi mereka, tetapi juga keberadaan seluruh umat manusia.', 'Action, Sci-Fi, Adventure', 115, '13+', 'English / Sub ID', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/lV1OOlGwExM', '2024-03-27', 'NOW_SHOWING'),
('Agak Laen', 'Empat sekawan penjaga rumah hantu di pasar malam terpaksa menyembunyikan mayat seorang pengunjung yang meninggal karena kaget. Rumah hantu mereka malah mendadak viral karena dianggap seram beneran oleh para pengunjung!', 'Comedy, Horror', 119, '13+', 'Bahasa Indonesia', 'https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/8Qn_spdM5Zg', '2024-02-01', 'NOW_SHOWING'),
('Inside Out 2', 'Riley kini menginjak usia remaja dan markas emosinya mengalami renovasi mendadak. Joy, Sadness, Anger, Fear, dan Disgust kini harus beradaptasi untuk memberi ruang bagi kelompok emosi baru yang dipimpin oleh Anxiety.', 'Animation, Family, Comedy', 96, 'SU', 'English / Sub ID', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/LEjhY15eCx0', '2024-06-14', 'NOW_SHOWING'),
('The Boy and the Heron', 'Setelah kehilangan ibunya selama Perang Dunia II, Mahito yang berusia 12 tahun pindah ke pedesaan. Di sana ia dibimbing oleh burung cangak misterius menuju dunia fantastis di mana yang hidup dan yang mati saling berdampingan.', 'Animation, Fantasy, Adventure', 124, '13+', 'Japanese / Sub ID', 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/t5khm-VjEu4', '2023-11-29', 'NOW_SHOWING'),

-- 6 FILM YANG TAYANG BESOK / AKAN RILIS DALAM WAKTU DEKAT (status = COMING_SOON)
('Deadpool & Wolverine', 'Wade Wilson yang sedang menjalani kehidupan tenang mendadak direkrut oleh Time Variance Authority (TVA) untuk sebuah misi multiversal. Ia terpaksa harus berkerjasama dengan Wolverine yang bersikap sinis dan enggan membantunya.', 'Action, Comedy, Sci-Fi', 127, '17+', 'English / Sub ID', 'https://images.unsplash.com/photo-1626814026160-2237a95fc5a0?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/TcMBFSGVi1c', '2024-07-24', 'COMING_SOON'),
('Joker: Folie à Deux', 'Arthur Fleck yang dikurung di Arkham Asylum saat menunggu persidangan atas kejahatannya sebagai Joker, menemukan cinta sejati saat bertemu dengan Harleen Quinzel. Bersamaan dengan itu, ia menemukan musik yang selama ini terpendam di dalam dirinya.', 'Drama, Musical, Thriller', 138, '17+', 'English / Sub ID', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/xy8aJw1vYHo', '2024-10-02', 'COMING_SOON'),
('Venom: The Last Dance', 'Eddie Brock dan Symbiote Venom kini menjadi buronan yang diburu oleh kedua dunia mereka. Saat jaring ancaman semakin menyempit, mereka terpaksa mengambil keputusan berat yang akan menjadi akhir dari tarian terakhir mereka.', 'Action, Sci-Fi, Thriller', 109, '13+', 'English / Sub ID', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/u9Mv98Gr5pY', '2024-10-23', 'COMING_SOON'),
('Siksa Kubur', 'Setelah kedua orang tuanya menjadi korban bom bunuh diri, Sita menjadi tidak percaya agama. Ia bertekad mencari orang yang paling berdosa dan ikut dikubur bersamanya untuk membuktikan bahwa siksa kubur itu tidak ada.', 'Horror, Drama, Mystery', 117, '17+', 'Bahasa Indonesia', 'https://images.unsplash.com/photo-1505635552518-3448ff116af3?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/1Vnghdsjmd0', '2024-04-11', 'COMING_SOON'),
('Gladiator II', 'Bertahun-tahun setelah menyaksikan kematian Maximus, Lucius dipaksa memasuki Colosseum setelah rumahnya ditaklukkan oleh kaisar tiran. Dengan amarah di hatinya, Lucius harus melihat ke masa lalu untuk mengembalikan kejayaan Roma kepada rakyatnya.', 'Action, Adventure, Drama', 148, '17+', 'English / Sub ID', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/4rgYUipGJNo', '2024-11-13', 'COMING_SOON'),
('Mufasa: The Lion King', 'Rafiki menceritakan legenda Mufasa kepada cucunya, Simba dan Nala. Kisah perjalanannya dimulai sebagai anak singa yatim piatu yang sendirian hingga bertemu dengan Pangeran Taka dan membentuk ikatan persaudaraan sejati yang mengubah takdir kerajaan.', 'Animation, Adventure, Family', 118, 'SU', 'English / Sub ID', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80', 'https://www.youtube.com/embed/o17MF9vnabg', '2024-12-18', 'COMING_SOON');
